# Generated by Django 3.2.7 on 2022-06-28 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('1', '1_ГО'), ('2', '2_ОФ'), ('3', '3_ЖАФ'), ('4', '4_БФ'), ('5', '5_ТФ'), ('6', '6_НФ'), ('7', '7_КФ'), ('8', '8_БатФ')], max_length=300, verbose_name='Филиал')),
                ('start_date', models.DateField(verbose_name='Начало месяца')),
                ('start_cp', models.IntegerField(default=0, verbose_name='Сумма КП, сом')),
                ('end_date', models.DateField(verbose_name='Конец месяца')),
                ('end_bud', models.IntegerField(default=0, verbose_name='Бюджет на это число')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('kp_som', models.IntegerField(default=0, verbose_name='КП, сом')),
                ('kp_kol', models.IntegerField(default=0, verbose_name='КП, кол-во')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='month', to='excel.month')),
            ],
        ),
    ]
