# Generated by Django 3.2.7 on 2022-06-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало месяца')),
                ('end_date', models.DateField(verbose_name='Конец месяца')),
            ],
        ),
        migrations.RemoveField(
            model_name='month',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='month',
            name='start_date',
        ),
    ]
