# Generated by Django 3.2.7 on 2022-06-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_auto_20220628_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
