# Generated by Django 3.2.7 on 2022-06-28 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0003_date_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='month', to='excel.date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistic',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='month', to='excel.month'),
        ),
    ]
