# Generated by Django 3.2.7 on 2022-06-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0005_auto_20220628_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='branch',
            field=models.CharField(choices=[('1_ГО', '1_ГО'), ('2_ОФ', '2_ОФ'), ('3_ЖАФ', '3_ЖАФ'), ('4_БФ', '4_БФ'), ('5_ТФ', '5_ТФ'), ('6_НФ', '6_НФ'), ('7_КФ', '7_КФ'), ('8_БатФ', '8_БатФ')], max_length=300, null=True, verbose_name='Филиал'),
        ),
    ]
